# This file contains the tables of objects to detect,
# with names and descriptions in different languages

transhead = {'en': 'The most recently observed positions with candies and their characteristics:',
             'sv': 'De senast observerade positionerna med godis och deras kännetecken:',
             'de': 'Die zuletzt beobachteten Positionen mit Süßigkeiten und ihre Eigenschaften:',
             'fr': 'Les positions les plus récemment observées avec des bonbons et leurs caractéristiques',
             'es': 'Las posiciones más recientemente observadas con dulces y sus características:'
             }

transtable = {
    "Plopp": { 'en': ("Plopp", "red rectangular, milk chocolate with toffee"),
               'sv': ("Plopp", "röd rectangulär, ljus choklad med kola"),
               'de': ("Plopp", "rotes Rechteck, Milchschokolade mit Toffee"),
               'fr': ("Plopp", "rectangle rouge, chocolat au lait avec caramel"),
               'es': ("Plopp", "rectangulo rojo, chocolate con leche y caramelo")},
    "Lakridskola": { 'en': ("Licorice", "black round, licorice taste"),
                     'sv': ("Lakrits", "rund svart, lakrits-kola"),
                     'de': ("Lakritze", "schwarz rund, Lakritzgeschmack"),
                     'fr': ("réglisse", "ronde noire, saveur de réglisse"),
                     'es': ("Regaliz", "redondo negro, sabor a regaliz")},
    "Pearnut": { 'en': ("Nut cream pear", "green round, pear taste"),
                 'sv': ("Nötkräm päron", "rund grön, päronsmak"),
                 'de': ("Nusscreme Birne", "grün rund, Birnengeschmack"),
                 'fr': ("Poire à la crème de noix", "ronde verte, goût de poire"),
                 'es': ("Pera con crema de nueces", "redonda y verde, sabor a pera")},
    "Whitenut": { 'en': ("Nut cream original", "white round, nut taste"),
                  'sv': ("Nötkräm original", "rund vit, nötsmak"),
                  'de': ("Nusscreme Original", "weiß rund, nussiger Geschmack"),
                  'fr': ("Crème de noix originale", "ronde blanche, goût de noisette"),
                  'es': ("Crema de nueces original", "redonda y blanca, sabor a nuez")},
    "Marianne": { 'en': ("Marianne", "red white stripes, mint taste"),
                  'sv': ("Marianne", "röda-vit randig, mintsmak"),
                  'de': ("Marianne", "rote und weiße Streifen, Minzgeschmack"),
                  'fr': ("Marianne", "rayures rouges et blanches, saveur de menthe"),
                  'es': ("Marianne", "rayas rojas y blancas, sabor a menta")},
    "FazerMint": { 'en': ("Fazer mint", "silver, mint taste"),
                   'sv': ("Fazer mint", "silver, mintsmak"),
                   'de': ("Fazer Minze", "Silber, Minzgeschmack"),
                   'fr': ("Fazer mint", "argent, saveur de menthe"),
                   'es': ("Fazer mint", "plata, sabor a menta")},
    "Mars": { 'en': ("Mars", "black with red text, chocolate with toffee and nougat"),
              'sv': ("Mars", "svart med röd text, choklad med kola och nougat"),
              'de': ("Mars", "schwarz mit rotem Text, Schokolade mit Toffee und Nougat"),
              'fr': ("Mars", "noir avec texte rouge, chocolat au caramel et au nougat"),
              'es': ("Mars", "negro con texto rojo, chocolate con toffee y turrón")},
    "Snickers": { 'en': ("Snickers", "brown with blue text, chocolate with nougat and peanuts"),
                  'sv': ("Snickers", "brun med blå text, choklad med nougat och jordnötter"),
                  'de': ("Snickers", "braun mit blauem Text, Schokolade mit Nougat und Erdnüssen"),
                  'fr': ("Snickers", "marron avec texte bleu, chocolat au nougat et aux cacahuètes"),
                  'es': ("Snickers", "marrón con texto azul, chocolate con turrón y cacahuetes")},
    "Geisha": { 'en': ("Geisha", "pink, chocolate with hazelnut nougat"),
                'sv': ("Geisha", "rosa, choklad med hasselnötsnougat"),
                'de': ("Geisha", "rosa, Schokolade mit Haselnussnougat"),
                'fr': ("Geisha", "rose, chocolat au nougat aux noisettes"),
                'es': ("Geisha", "rosa, turrón de chocolate con avellanas")},
    "Dumle": { 'en': ("Dumle", "red, milk chocolate with toffee"),
               'sv': ("Dumle", "röd, ljus choklad med kola"),
               'de': ("Dumle", "rot, Milchschokolade mit Toffee"),
               'fr': ("Dumle", "rouge, chocolat au lait avec caramel"),
               'es': ("Dumle", "rojo, chocolate con leche y caramelo")},
    "VanillaFudge": { 'en': ("Vanilla fudge", "beige, vanilla fudge"),
                      'sv': ("Gräddkola", "beige, vanilj-smak"),
                      'de': ("Vanille-Fudge", "Beige, Vanillegeschmack"),
                      'fr': ("Fudge à la vanille", "beige, saveur de vanille"),
                      'es': ("Fudge de vainilla", "beige, sabor a vainilla")},
    "Riesen": { 'en': ("Riesen toffee", "brown with yellow text, dark chocolate toffee"),
                'sv': ("Riesen-kola", "brun med gul text, mörk choklad-kola"),
                'de': ("Riesen Toffee", "braun mit gelber Schrift, dunkles Schokoladen-Toffee"),
                'fr': ("Riesen toffee", "marron avec texte jaune, caramel au chocolat noir"),
                'es': ("Caramelo Riesen", "marrón con texto amarillo, caramelo de chocolate negro")},
    "Refreshers": { 'en': ("Refreshers", "blue rectangular with red text, lemon taste"),
                    'sv': ("Refreshers", "blå rectangulär med röd text, citronsmak"),
                    'de': ("Refreshers", "blaues Rechteck mit rotem Text, Zitronengeschmack"),
                    'fr': ("Refreshers", "rectangle bleu avec texte rouge, saveur de citron"),
                    'es': ("Refreshers", "rectángulo azul con texto rojo, sabor a limón")},
    }
