[project]
name = "xledplus_mcp"
version = "0.1.0"
description = "An MCP-server to control a Twinkly LED light string."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.3.4",
    "xled_plus",
]
