[project]
name = "face-recognition"
version = "0.1.0"
description = "Face recognition app that learns faces over time"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.11,<3.13"
dlib = "*"
numpy = "*"
face_recognition = "*"
face_recognition_models = "*"
setuptools = "<80"
python-sounddevice = "*"
scipy = "*"
opencv = ">=4.13.0,<5"

[pypi-dependencies]
piper-tts = "*"
faster-whisper = "*"
onnxruntime = ">=1.23.2, <2"
torch = "*"
torchaudio = "*"
noisereduce = "*"
pydantic-ai = {version = "*", extras = ["openai", "mcp"]}
livekit = ">=1.1.5, <2"

[tasks]
run = "python main.py"
vision = "python face_tracker.py"
listen = "python voice_input.py"
people = "python people_memory.py"
shell = "python people_memory.py shell"
speak = "python voice_output.py"
agent = "python agent.py"
