[project]
name = "mcpscreen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.3.4",
    "ollama>=0.4.8",
    "opencv-python>=4.11.0.86",
]
