[project]
name = "mcpclient_text"
version = "0.1.0"
description = "Generic LLM-based MCP-client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "fastmcp>=2.3.4",
]
