[project]
name = "mcpscreen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "fastmcp>=2.3.4",
    "matplotlib",
    "pyaudio",
]
